// Generated by `collabnode types`. Do not edit — regenerate instead.
// Source: ../workspaces/solution-planner.yaml
// Schema: SolutionPlannerGraph v1 (82ff9dd0eaf95ca5128a15c6cec4c76b9e9984afa9f1c72f8a5f45855cde9540)

import type {
  Equal,
  Expect,
  GraphNodeRecord,
  GraphTypes,
  NodeInput,
  NodeProps,
  StrictInput,
  WorkspaceTypeLiteral,
} from "collabnode";

/** The schema hash this module was generated from. */
export const SCHEMA_HASH = "82ff9dd0eaf95ca5128a15c6cec4c76b9e9984afa9f1c72f8a5f45855cde9540";

/**
 * The solution-planner workspace, trimmed to what the types read. Regenerate
 * with `--full` for a runtime-usable value.
 */
export const solutionPlanner = {
  "name": "solution-planner",
  "version": 1,
  "schema": {
    "name": "SolutionPlannerGraph",
    "version": 1,
    "schemaHash": "82ff9dd0eaf95ca5128a15c6cec4c76b9e9984afa9f1c72f8a5f45855cde9540",
    "config": {
      "schemaId": "solution-planner"
    },
    "nodes": {
      "SolutionState": {
        "properties": {
          "appName": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "language": {
            "type": "enum",
            "default": "en",
            "values": [
              "en",
              "es"
            ]
          },
          "status": {
            "type": "enum",
            "default": "idle",
            "values": [
              "idle",
              "planning",
              "waiting_user_validation",
              "approved"
            ]
          },
          "managerAgrees": {
            "type": "boolean",
            "default": false
          },
          "architectAgrees": {
            "type": "boolean",
            "default": false
          },
          "iteration": {
            "type": "number",
            "default": 0
          },
          "pendingAssumptionId": {
            "type": "string"
          },
          "activeAgent": {
            "type": "enum",
            "default": "none",
            "values": [
              "none",
              "manager",
              "architect"
            ]
          },
          "mode": {
            "type": "enum",
            "default": "initial",
            "values": [
              "initial",
              "revise"
            ]
          }
        }
      },
      "Epic": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "priority": {
            "type": "enum",
            "default": "medium",
            "values": [
              "low",
              "medium",
              "high"
            ]
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "Feature": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "C4DiagramElement": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "type": {
            "type": "enum",
            "required": true,
            "values": [
              "Person",
              "System",
              "Boundary",
              "Container",
              "Component"
            ]
          },
          "description": {
            "type": "text"
          },
          "technology": {
            "type": "string"
          },
          "external": {
            "type": "boolean",
            "default": false
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "Task": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "functionalPoints": {
            "type": "number",
            "default": 1
          },
          "technicalPoints": {
            "type": "number",
            "default": 1
          },
          "complexity": {
            "type": "number",
            "default": 1
          },
          "uncertainty": {
            "type": "number",
            "default": 1
          },
          "friction": {
            "type": "number",
            "default": 1
          },
          "nfrScale": {
            "type": "number",
            "default": 0
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "Risk": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "severity": {
            "type": "enum",
            "default": "medium",
            "values": [
              "low",
              "medium",
              "high",
              "critical"
            ]
          },
          "category": {
            "type": "enum",
            "default": "business",
            "values": [
              "business",
              "technical"
            ]
          },
          "mitigation": {
            "type": "text"
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "Assumption": {
        "properties": {
          "title": {
            "type": "string",
            "required": true
          },
          "description": {
            "type": "text"
          },
          "status": {
            "type": "enum",
            "default": "pending",
            "values": [
              "pending",
              "approved",
              "rejected"
            ]
          },
          "raisedBy": {
            "type": "enum",
            "default": "manager",
            "values": [
              "manager",
              "architect",
              "human"
            ]
          },
          "userComment": {
            "type": "text"
          },
          "dirty": {
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "edges": {
      "HAS_FEATURE": {
        "from": [
          "Epic"
        ],
        "to": [
          "Feature"
        ],
        "directed": true,
        "properties": {}
      },
      "HAS_TASK": {
        "from": [
          "Feature"
        ],
        "to": [
          "Task"
        ],
        "directed": true,
        "properties": {}
      },
      "HAS_RISK": {
        "from": [
          "Epic",
          "Feature",
          "Task",
          "C4DiagramElement"
        ],
        "to": [
          "Risk"
        ],
        "directed": true,
        "properties": {}
      },
      "HAS_ASSUMPTION": {
        "from": [
          "Epic",
          "Feature",
          "Task"
        ],
        "to": [
          "Assumption"
        ],
        "directed": true,
        "properties": {}
      },
      "CONTAINS": {
        "from": [
          "C4DiagramElement"
        ],
        "to": [
          "C4DiagramElement"
        ],
        "directed": true,
        "properties": {}
      },
      "USES": {
        "from": [
          "C4DiagramElement"
        ],
        "to": [
          "C4DiagramElement"
        ],
        "directed": true,
        "properties": {}
      },
      "TARGETS_C4": {
        "from": [
          "Task"
        ],
        "to": [
          "C4DiagramElement"
        ],
        "directed": true,
        "properties": {}
      }
    }
  }
} as const satisfies WorkspaceTypeLiteral;

/**
 * Every type this workspace contributes, in one map. Pass it wherever a
 * session, hook or plan is generic over a schema.
 */
export type SolutionPlanner = GraphTypes<typeof solutionPlanner>;

export type NodeTypeName = keyof SolutionPlanner["nodes"] & string;
export type EdgeTypeName = keyof SolutionPlanner["edges"] & string;

/**
 * High-level solution planning state and consensus tracking
 */
export interface SolutionStateProps {
  appName: string;
  description: string;
  language: "en" | "es";
  status: "idle" | "planning" | "waiting_user_validation" | "approved";
  managerAgrees: boolean;
  architectAgrees: boolean;
  iteration: number;
  pendingAssumptionId?: string;
  activeAgent: "none" | "manager" | "architect";
  mode: "initial" | "revise";
}

/** Compile-time proof that `SolutionStateProps` still matches what the schema implies. */
export type _AssertSolutionStateProps = Expect<Equal<SolutionStateProps, NodeProps<typeof solutionPlanner, "SolutionState">>>;

/** `SolutionState` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type SolutionStateInput = NodeInput<typeof solutionPlanner, "SolutionState">;
/** `SolutionState` as a model answers it under structured output's strict mode. */
export type SolutionStateStrict = StrictInput<typeof solutionPlanner, "SolutionState">;
/** A `SolutionState` node record, with its id, tags and provenance. */
export type SolutionStateNode = GraphNodeRecord<SolutionPlanner, "SolutionState">;

/**
 * High-level business initiative or milestone. Owns its Features through
 * HAS_FEATURE edges.
 *
 * - An Epic owns a Feature only through a HAS_FEATURE edge. There is no
 *   title/parent property that stands in for it.
 */
export interface EpicProps {
  title: string;
  description: string;
  priority: "low" | "medium" | "high";
  /** Human-changed, not yet revised by the Manager/Architect crew */
  dirty: boolean;
}

/** Compile-time proof that `EpicProps` still matches what the schema implies. */
export type _AssertEpicProps = Expect<Equal<EpicProps, NodeProps<typeof solutionPlanner, "Epic">>>;

/** `Epic` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type EpicInput = NodeInput<typeof solutionPlanner, "Epic">;
/** `Epic` as a model answers it under structured output's strict mode. */
export type EpicStrict = StrictInput<typeof solutionPlanner, "Epic">;
/** An `Epic` node record, with its id, tags and provenance. */
export type EpicNode = GraphNodeRecord<SolutionPlanner, "Epic">;

/**
 * Concrete functional capability. Reached from its Epic by HAS_FEATURE, and
 * owns its Tasks by HAS_TASK.
 *
 * - A Feature belongs to exactly one Epic, and that link is the HAS_FEATURE
 *   edge — never an epicTitle string.
 * - Every Feature you create must be linked to its Epic in the same write.
 */
export interface FeatureProps {
  title: string;
  description: string;
  /** Human-changed, not yet revised by the Manager/Architect crew */
  dirty: boolean;
}

/** Compile-time proof that `FeatureProps` still matches what the schema implies. */
export type _AssertFeatureProps = Expect<Equal<FeatureProps, NodeProps<typeof solutionPlanner, "Feature">>>;

/** `Feature` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type FeatureInput = NodeInput<typeof solutionPlanner, "Feature">;
/** `Feature` as a model answers it under structured output's strict mode. */
export type FeatureStrict = StrictInput<typeof solutionPlanner, "Feature">;
/** A `Feature` node record, with its id, tags and provenance. */
export type FeatureNode = GraphNodeRecord<SolutionPlanner, "Feature">;

/**
 * One C4 element. The `type` property is Person, System, Boundary,
 * Container, or Component. `external` renders as Mermaid _Ext.
 *
 * - A container diagram alone is not a C4 model. Model every level that
 *   applies - at least one Person for who uses the solution, one Boundary
 *   for the system being designed, a System with external:true per
 *   third-party system it talks to, and Components inside the Container that
 *   carries the most logic.
 * - Boundary groups; System is software. Never model the solution itself as
 *   both.
 * - Nesting is the CONTAINS edge (Boundary CONTAINS Container, Container
 *   CONTAINS Component), and a call between elements is the USES edge. Never
 *   write a parent's title into a property.
 */
export interface C4DiagramElementProps {
  title: string;
  /** C4 element kind. Boundary is grouping only; System is software. Never mix them. */
  type: "Person" | "System" | "Boundary" | "Container" | "Component";
  description: string;
  technology?: string;
  /** When true, Mermaid uses Person_Ext / System_Ext / Container_Ext / ContainerDb_Ext */
  external: boolean;
  dirty: boolean;
}

/** Compile-time proof that `C4DiagramElementProps` still matches what the schema implies. */
export type _AssertC4DiagramElementProps = Expect<Equal<C4DiagramElementProps, NodeProps<typeof solutionPlanner, "C4DiagramElement">>>;

/** `C4DiagramElement` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type C4DiagramElementInput = NodeInput<typeof solutionPlanner, "C4DiagramElement">;
/** `C4DiagramElement` as a model answers it under structured output's strict mode. */
export type C4DiagramElementStrict = StrictInput<typeof solutionPlanner, "C4DiagramElement">;
/** A `C4DiagramElement` node record, with its id, tags and provenance. */
export type C4DiagramElementNode = GraphNodeRecord<SolutionPlanner, "C4DiagramElement">;

/**
 * Actionable implementation task with a What/How description and
 * functional/technical story points. Reached from its Feature by HAS_TASK.
 *
 * - functionalPoints and technicalPoints are integers from 1 to 21 — never a
 *   sentence. Estimate on the Fibonacci ladder (1, 2, 3, 5, 8, 13, 21) by
 *   convention.
 * - Put What (functional outcome) and How (technical approach) in
 *   description, using the labels "What:" and "How:".
 * - A Task implements exactly one Feature, and that link is the HAS_TASK
 *   edge — never a featureTitle string. Link every Task you create.
 * - Point a Task at the C4 element it changes with TARGETS_C4 when one
 *   applies.
 */
export interface TaskProps {
  title: string;
  /** Must include What (functional outcome / user journey) and How (technical approach, infrastructure, integrations) */
  description: string;
  /** Functional-effort story points, integer 1-21. Fibonacci by convention. Never a sentence. From 1 to 21. */
  functionalPoints: number;
  /** Technical-effort story points, integer 1-21. Fibonacci by convention. Never a sentence. From 1 to 21. */
  technicalPoints: number;
  /** 0 (Trivial) to 5 (Massive architectural overhaul) */
  complexity: number;
  /** 0 (Done 100x) to 5 (Pure R&D) */
  uncertainty: number;
  /** 0 (Solo work) to 5 (Heavy cross-team coordination) */
  friction: number;
  /** 0 (Low/Internal) to 3 (Extreme compliance/scale) */
  nfrScale: number;
  /** Human-changed, not yet revised by the Manager/Architect crew */
  dirty: boolean;
}

/** Compile-time proof that `TaskProps` still matches what the schema implies. */
export type _AssertTaskProps = Expect<Equal<TaskProps, NodeProps<typeof solutionPlanner, "Task">>>;

/** `Task` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type TaskInput = NodeInput<typeof solutionPlanner, "Task">;
/** `Task` as a model answers it under structured output's strict mode. */
export type TaskStrict = StrictInput<typeof solutionPlanner, "Task">;
/** A `Task` node record, with its id, tags and provenance. */
export type TaskNode = GraphNodeRecord<SolutionPlanner, "Task">;

/**
 * Identified business or technical risk with mitigation strategy
 */
export interface RiskProps {
  title: string;
  description: string;
  severity: "low" | "medium" | "high" | "critical";
  category: "business" | "technical";
  mitigation: string;
  /** Human-changed, not yet revised by the Manager/Architect crew */
  dirty: boolean;
}

/** Compile-time proof that `RiskProps` still matches what the schema implies. */
export type _AssertRiskProps = Expect<Equal<RiskProps, NodeProps<typeof solutionPlanner, "Risk">>>;

/** `Risk` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type RiskInput = NodeInput<typeof solutionPlanner, "Risk">;
/** `Risk` as a model answers it under structured output's strict mode. */
export type RiskStrict = StrictInput<typeof solutionPlanner, "Risk">;
/** A `Risk` node record, with its id, tags and provenance. */
export type RiskNode = GraphNodeRecord<SolutionPlanner, "Risk">;

/**
 * Critical assumption requiring human-in-the-loop validation
 */
export interface AssumptionProps {
  title: string;
  description: string;
  status: "pending" | "approved" | "rejected";
  raisedBy: "manager" | "architect" | "human";
  userComment: string;
  /** Human-changed, not yet revised by the Manager/Architect crew */
  dirty: boolean;
}

/** Compile-time proof that `AssumptionProps` still matches what the schema implies. */
export type _AssertAssumptionProps = Expect<Equal<AssumptionProps, NodeProps<typeof solutionPlanner, "Assumption">>>;

/** `Assumption` as `upsertNode` accepts it. Derived properties are absent; optional ones accept `null` to clear. */
export type AssumptionInput = NodeInput<typeof solutionPlanner, "Assumption">;
/** `Assumption` as a model answers it under structured output's strict mode. */
export type AssumptionStrict = StrictInput<typeof solutionPlanner, "Assumption">;
/** An `Assumption` node record, with its id, tags and provenance. */
export type AssumptionNode = GraphNodeRecord<SolutionPlanner, "Assumption">;

// Edge endpoints, as declared in the schema.
/**
 * The Epic this Feature belongs to. The only way a Feature is attached to an
 * Epic.
 *
 * - Create this edge in the same write as the Feature. An unlinked Feature
 *   is not in the plan.
 * - One Epic per Feature. To move a Feature, delete the old edge and create
 *   the new one.
 */
export type HasFeatureEdge = { from: "Epic"; to: "Feature" };
/**
 * The Feature this Task implements. The only way a Task is attached to the
 * plan.
 *
 * - Create this edge in the same write as the Task. An unlinked Task is not
 *   estimated against any Feature.
 * - One Feature per Task. To move a Task, delete the old edge and create the
 *   new one.
 */
export type HasTaskEdge = { from: "Feature"; to: "Task" };
/**
 * What this Risk threatens — the Epic, Feature, Task, or C4 element it
 * applies to.
 *
 * - Link every Risk to what it threatens. A floating Risk cannot be triaged.
 */
export type HasRiskEdge = { from: "Epic" | "Feature" | "Task" | "C4DiagramElement"; to: "Risk" };
/**
 * What this Assumption is load-bearing for — the Epic, Feature, or Task that
 * depends on it.
 */
export type HasAssumptionEdge = { from: "Epic" | "Feature" | "Task"; to: "Assumption" };
/**
 * C4 nesting - a Boundary contains its Containers, a Container contains its
 * Components.
 */
export type ContainsEdge = { from: "C4DiagramElement"; to: "C4DiagramElement" };
/**
 * A C4 element calls or depends on another (a Mermaid Rel line).
 */
export type UsesEdge = { from: "C4DiagramElement"; to: "C4DiagramElement" };
/**
 * The C4 element a Task builds or changes.
 */
export type TargetsC4Edge = { from: "Task"; to: "C4DiagramElement" };
