import { resolveGuidelines, resolveI18nString } from "./i18n.js";
import { isCrdtPropertyType } from "./types.js";
import type {
  EdgeTypeDef,
  GraphSchema,
  NodeTypeDef,
  PropertyDef,
  WorkspaceType,
} from "./types.js";

/**
 * A workspace schema as a TypeScript module.
 *
 * The emitted module has two halves. The literal — the schema itself, `as const`
 * — is the source of truth, and every type in the file is inferred from it by
 * `GraphTypes`. The explicit `…Props` interfaces exist only so the editor has
 * something to show: a type produced by a mapped type cannot carry per-property
 * JSDoc, and throwing away the descriptions the YAML already carries would be a
 * poor trade in the one place they are most useful. They are not a second source
 * of truth — the generator emits an `Expect<Equal<…>>` beside each one, so an
 * interface that stops matching the inferred shape is a compile error in the
 * generated file itself.
 */

export interface EmitTypescriptOptions {
  /** Base identifier for the emitted const and type. Defaults to the workspace name. */
  name?: string;
  /** Where the generated module imports library types from. */
  importFrom?: string;
  /**
   * Emit the whole workspace rather than only the fields the types read.
   *
   * The default keeps property definitions, edge endpoints and the schema id —
   * a few KB. `full` also keeps descriptions, guidelines, prompts, views and
   * templates, which makes the const usable as a runtime `WorkspaceType`: an
   * app can import it instead of parsing YAML, and a browser instead of
   * fetching it.
   */
  full?: boolean;
  /** Path shown in the header comment. */
  source?: string;
  /** Language for the prose pulled out of the YAML's i18n strings. */
  language?: string;
}

const HEADER = "Generated by `collabnode types`. Do not edit — regenerate instead.";

export function workspaceToTypescript(
  type: WorkspaceType,
  options: EmitTypescriptOptions = {},
): string {
  const { importFrom = "collabnode", full = false, source, language } = options;
  const base = identifier(options.name ?? type.name ?? type.schema.name);
  const constName = lowerFirst(base);
  const typeName = upperFirst(base);
  const schema = type.schema;

  const literal = full ? type : trimWorkspace(type);
  const out: string[] = [];

  out.push(`// ${HEADER}`);
  if (source) {
    out.push(`// Source: ${source}`);
  }
  out.push(`// Schema: ${schema.name} v${schema.version} (${schema.schemaHash})`);
  out.push("");
  out.push(`import type {`);
  out.push(`  Equal,`);
  out.push(`  Expect,`);
  out.push(`  GraphNodeRecord,`);
  out.push(`  GraphTypes,`);
  out.push(`  NodeInput,`);
  out.push(`  NodeProps,`);
  out.push(`  StrictInput,`);
  out.push(`  WorkspaceTypeLiteral,`);
  out.push(`} from ${JSON.stringify(importFrom)};`);
  out.push("");
  out.push(`/** The schema hash this module was generated from. */`);
  out.push(`export const SCHEMA_HASH = ${JSON.stringify(schema.schemaHash)};`);
  out.push("");
  out.push(
    ...docComment(
      full
        ? `The ${type.name} workspace. Usable as a runtime WorkspaceType as well as a type source.`
        : `The ${type.name} workspace, trimmed to what the types read. Regenerate with \`--full\` for a runtime-usable value.`,
      [],
    ),
  );
  out.push(`export const ${constName} = ${literalText(literal)} as const satisfies WorkspaceTypeLiteral;`);
  out.push("");
  out.push(
    ...docComment(
      `Every type this workspace contributes, in one map. Pass it wherever a session, hook or plan is generic over a schema.`,
      [],
    ),
  );
  out.push(`export type ${typeName} = GraphTypes<typeof ${constName}>;`);
  out.push("");
  out.push(`export type NodeTypeName = keyof ${typeName}["nodes"] & string;`);
  out.push(`export type EdgeTypeName = keyof ${typeName}["edges"] & string;`);
  out.push("");

  for (const [name, def] of Object.entries(schema.nodes)) {
    out.push(...nodeBlock(name, def, { constName, typeName, language }));
    out.push("");
  }

  out.push("// Edge endpoints, as declared in the schema.");
  for (const [name, def] of Object.entries(schema.edges)) {
    const from = def.from.map((t) => JSON.stringify(t)).join(" | ") || "string";
    const to = def.to.map((t) => JSON.stringify(t)).join(" | ") || "string";
    const desc = resolveI18nString(def.description, language);
    if (desc) {
      out.push(...docComment(desc, resolveGuidelines(def.guidelines, language)));
    }
    out.push(`export type ${identifier(name)}Edge = { from: ${from}; to: ${to} };`);
  }
  out.push("");

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

interface NodeBlockContext {
  constName: string;
  typeName: string;
  language?: string;
}

function nodeBlock(name: string, def: NodeTypeDef, ctx: NodeBlockContext): string[] {
  const id = identifier(name);
  const out: string[] = [];
  const description = resolveI18nString(def.description, ctx.language);
  const guidelines = resolveGuidelines(def.guidelines, ctx.language);

  out.push(
    ...docComment(
      description || `\`${name}\` as it comes back from a snapshot.`,
      guidelines,
    ),
  );
  out.push(`export interface ${id}Props {`);
  for (const [key, prop] of Object.entries(def.properties)) {
    const doc = propertyDoc(prop, ctx.language);
    if (doc) {
      out.push(`  /** ${doc} */`);
    }
    out.push(`  ${readMember(key, prop)};`);
  }
  out.push(`}`);
  out.push("");
  out.push(
    `/** Compile-time proof that \`${id}Props\` still matches what the schema implies. */`,
  );
  out.push(
    `export type _Assert${id}Props = Expect<Equal<${id}Props, NodeProps<typeof ${ctx.constName}, ${JSON.stringify(name)}>>>;`,
  );
  out.push("");
  out.push(`/** \`${name}\` as \`upsertNode\` accepts it. Derived properties are absent; optional ones accept \`null\` to clear. */`);
  out.push(
    `export type ${id}Input = NodeInput<typeof ${ctx.constName}, ${JSON.stringify(name)}>;`,
  );
  out.push(`/** \`${name}\` as a model answers it under structured output's strict mode. */`);
  out.push(
    `export type ${id}Strict = StrictInput<typeof ${ctx.constName}, ${JSON.stringify(name)}>;`,
  );
  out.push(`/** ${article(name)} \`${name}\` node record, with its id, tags and provenance. */`);
  out.push(
    `export type ${id}Node = GraphNodeRecord<${ctx.typeName}, ${JSON.stringify(name)}>;`,
  );
  return out;
}

/**
 * How a property appears on a read.
 *
 * Mirrors `ReadRequiredKeys` in `infer.ts`, which in turn mirrors the runtime:
 * a default is filled in on create, and a CRDT field is materialized by
 * `hydrateNode` on every snapshot, so both are always there. A derived property
 * is computed, so it is `readonly`, and it disappears when its inputs do.
 */
function readMember(key: string, prop: PropertyDef): string {
  const type = readType(prop);
  if (prop.derived !== undefined) {
    return `readonly ${memberName(key)}?: ${type}`;
  }
  const always = prop.required === true || prop.default !== undefined || isCrdtPropertyType(prop.type);
  return always ? `${memberName(key)}: ${type}` : `${memberName(key)}?: ${type}`;
}

function readType(prop: PropertyDef): string {
  switch (prop.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "enum": {
      const values = prop.values ?? [];
      return values.length > 0 ? values.map((v) => JSON.stringify(v)).join(" | ") : "string";
    }
    case "map":
      return "Record<string, unknown>";
    case "array":
      return "unknown[]";
    default:
      // string, text, datetime and json all read back as strings — the runtime
      // stringifies json on the way in.
      return "string";
  }
}

/**
 * The property's own prose, plus the bounds the schema declares.
 *
 * The bounds are worth repeating here for the same reason `strictDef` repeats
 * them for a model: they are real constraints that the type system cannot carry,
 * so the only place a developer will see them is on hover.
 */
function propertyDoc(prop: PropertyDef, language?: string): string {
  const parts: string[] = [];
  const described = resolveI18nString(prop.description, language);
  if (described) {
    parts.push(described.trim());
  }
  if (prop.type === "datetime") {
    parts.push("ISO 8601 datetime.");
  }
  if (prop.min !== undefined && prop.max !== undefined) {
    parts.push(`From ${prop.min} to ${prop.max}.`);
  } else if (prop.min !== undefined) {
    parts.push(`At least ${prop.min}.`);
  } else if (prop.max !== undefined) {
    parts.push(`At most ${prop.max}.`);
  }
  if (prop.maxLength !== undefined) {
    parts.push(`At most ${prop.maxLength} characters.`);
  }
  if (prop.derived !== undefined) {
    parts.push(`Derived: \`${prop.derived}\`. Computed by the runtime; writes are ignored.`);
  }
  return escapeDoc(parts.join(" ").replace(/\s+/g, " ").trim());
}

/**
 * Prose from a schema YAML lands inside a JSDoc block, where a comment-closing
 * star-slash would end it early and leave the generated module unparseable.
 */
function escapeDoc(text: string): string {
  return text.replace(/\*\//g, "*\\/");
}

function docComment(summary: string, guidelines: string[]): string[] {
  const body = escapeDoc(summary.trim());
  if (!body && guidelines.length === 0) {
    return [];
  }
  const lines = ["/**"];
  for (const line of wrap(body, 74)) {
    lines.push(` * ${line}`);
  }
  if (guidelines.length > 0) {
    if (body) {
      lines.push(" *");
    }
    for (const guideline of guidelines) {
      const wrapped = wrap(escapeDoc(guideline.trim()), 72);
      lines.push(` * - ${wrapped[0] ?? ""}`);
      for (const cont of wrapped.slice(1)) {
        lines.push(` *   ${cont}`);
      }
    }
  }
  lines.push(" */");
  return lines;
}

function wrap(text: string, width: number): string[] {
  if (!text) {
    return [];
  }
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line && line.length + word.length + 1 > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) {
    lines.push(line);
  }
  return lines;
}

/** Type names are the schema author's words, and they land in generated prose. */
function article(name: string): string {
  return /^[AEIOU]/i.test(name) ? "An" : "A";
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function memberName(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

/**
 * Only the fields a type is derived from.
 *
 * A parsed workspace is mostly prose — descriptions in every language,
 * guidelines, system prompts, view definitions, templates. None of it changes a
 * single emitted type, and all of it would land in the `as const` for the
 * compiler to walk on every check.
 */
function trimWorkspace(type: WorkspaceType): Record<string, unknown> {
  return {
    name: type.name,
    version: type.version,
    schema: trimSchema(type.schema),
  };
}

function trimSchema(schema: GraphSchema): Record<string, unknown> {
  return {
    name: schema.name,
    version: schema.version,
    schemaHash: schema.schemaHash,
    config: { schemaId: schema.config.schemaId },
    nodes: Object.fromEntries(
      Object.entries(schema.nodes).map(([name, def]) => [name, trimNode(def)]),
    ),
    edges: Object.fromEntries(
      Object.entries(schema.edges).map(([name, def]) => [name, trimEdge(def)]),
    ),
  };
}

function trimNode(def: NodeTypeDef): Record<string, unknown> {
  return { properties: trimProperties(def.properties) };
}

function trimEdge(def: EdgeTypeDef): Record<string, unknown> {
  return {
    from: [...def.from],
    to: [...def.to],
    directed: def.directed,
    properties: trimProperties(def.properties),
  };
}

function trimProperties(
  properties: Record<string, PropertyDef>,
): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {};
  for (const [name, def] of Object.entries(properties)) {
    const trimmed: Record<string, unknown> = { type: def.type };
    if (def.required !== undefined) trimmed.required = def.required;
    if (def.default !== undefined) trimmed.default = def.default;
    if (def.values !== undefined) trimmed.values = [...def.values];
    if (def.derived !== undefined) trimmed.derived = def.derived;
    out[name] = trimmed;
  }
  return out;
}

/** JSON is valid TypeScript, and quoting every key sidesteps reserved words. */
function literalText(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

/**
 * A schema name as a TypeScript identifier.
 *
 * Edge types are conventionally `SCREAMING_SNAKE`, and stripping the separators
 * alone turns `LINKS_TO` into `LINKSTO`. Those get case-folded per word; a name
 * that already carries lowercase letters is the author's own casing —
 * `C4DiagramElement` — and is left exactly as written.
 */
function identifier(name: string): string {
  const screaming = /^[A-Z0-9_]+$/.test(name);
  const source = screaming
    ? name
        .split("_")
        .filter(Boolean)
        .map((word) => word.charAt(0) + word.slice(1).toLowerCase())
        .join("")
    : name;
  const cleaned = source.replace(/[^A-Za-z0-9]+(.)?/g, (_m, chr: string | undefined) =>
    chr ? chr.toUpperCase() : "",
  );
  const safe = cleaned.replace(/^[^A-Za-z_$]+/, "");
  return safe || "Workspace";
}

function upperFirst(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}
